### ISSUE TITLE
NullPointerException at com.hauldata.dbpa.datasource.DataSource.getColumnCount(DataSource.java:49)

### ISSUE THREAD

**Issue by rdesantis** [rdesantis/hauldata#74]
Report_W_TPEP-LPEP[REPORT_TPEP].PostXpep2Reports[FOREACHREPORT.POSTIT:TripRecord-async].PostTlcReport,CREATECSV,2018-04-25T10:37:47.811,2,"java.lang.NullPointerException at com.hauldata.dbpa.datasource.DataSource.getColumnCount(DataSource.java:49)"

**Comment by rdesantis** [comment]
Problem is due to void com.hauldata.dbpa.process.DbProcess.run(String[] args, Context context).  In the finally clause it runs context.close(connections) which forces database connection closed.  But in asynchronous nested scripts, the database connection is shared among them.  So when the first task completes, the connection is closed for all remaining tasks.

Must not close if DatabaseConnection.connCount > 0.

But also need assurance that we don't leak connections.  So the ultimate caller to outer DbProcess.run() must force all connections closed.  None should be open at that time unless we have a memory leak.

**Comment by rdesantis** [comment]
May be fixed by https://github.com/rdesantis/hauldata/commit/7ac1ac6e47efafe8a6ace15635680f2e7ec3e050.  Must confirm

**Comment by rdesantis** [comment]
This bug no longer occurs in release 1.12.1 which has concurrency fixes.

See https://github.com/rdesantis/hauldata/releases/tag/v1.12.1
